version: '3'
services:
  app:
    environment: 
      - RAILS_ENV=development
    volumes:
      - .:/app
    ports:
      - 3010:3009
      - 3035:3035
  sidekiq:
    volumes:
      - .:/app
    environment: 
      - RAILS_ENV=development