development:
  adapter: redis
  url: redis://redis:6379
  channel_prefix: shopify_dev
test:
  adapter: redis
  url: redis://redis:6379
  channel_prefix: shopify_test

production:
  adapter: redis
  url: redis://redis:6379
  channel_prefix: shopify_production
